---
- name: Install base packages
  become: yes
  include: system.yml
  tags: ['system']

- name: Set environment variables
  become: yes
  include: environment.yml
  tags: ['env']

- name: Create logging facilities
  become: yes
  include: logging.yml
  tags: ['logs']

- name: Configure Postgres
  become: yes
  include: database.yml
  tags: ['database']

- name: Configure RabbitMQ
  become: yes
  include: broker.yml
  tags: ['broker']

- name: Configure Redis
  become: yes
  include: redis.yml
  tags: ['redis']

- name: Install application
  become: no
  include: app.yml
  tags: ['app']

- name: Configure Celery
  become: yes
  include: celery.yml
  tags: ['celery']

- name: Configure Nginx server
  become: yes
  include: server.yml
  tags: ['server']

- name: Test if site is accessable
  become: no
  include: test.yml
  tags: ['test']
