---
# defaults file for ec2-deploy
repo_url: https://github.com/{{ github_user }}/{{ app_name }}.git
packages:
  - python3-pip
  - python3-dev
  - git
  - tree
  - nginx
pip_core:
  - pip
  - setuptools
  - wheel
python_core:
  - virtualenv
postgres_core:
  - postgresql
  - postgresql-contrib
  - postgresql-client-common
  - python3-psycopg2
os_environment:
  - key: SQLALCHEMY_DATABASE_URI
    value : postgresql+psycopg2://{{ postgres_user }}:{{ postgres_password }}@localhost:5432/{{ postgres_database }}
  - key: CELERY_BROKER_URL
    value : postgresql+psycopg2://{{ postgres_user }}:{{ postgres_password }}@localhost:5432/{{ postgres_database }}
  - key: FLASK_CONFIG_PATH
    value: ../config/staging.py
  - key: AUTH_TOKEN
    value: supersecrettoken

gunicorn_error_log: /home/{{ ansible_ssh_user }}/{{ app_name }}/gunicorn-error.log
gunicorn_access_log: /home/{{ ansible_ssh_user }}/{{ app_name }}/gunicorn-access.log
wsgi_path: "{{ entry_point }}.core.wsgi"
