---
# defaults file for ec2-deploy
packages:
  - python3-pip
  - python3-dev
  - git
  - tree
  - nginx
  - postgresql
  - postgresql-contrib

pip_core:
  - pip
  - setuptools
  - wheel

python_core:
  - virtualenv
  - psycopg2-binary

repo_url: https://github.com/{{ github_user }}/{{ app_name }}.git
