---
  # fetch source code and install
- name: Clone source repository
  git:
    repo: "{{ repo_url }}"
    dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
    update: yes  # Does a git pull if the repo already exists

- name: install modules in a virtualenv
  pip:
    requirements: /home/{{ ansible_ssh_user }}/{{ app_name }}/requirements.txt
    virtualenv: /home/{{ ansible_ssh_user }}/{{ app_name }}/env
    virtualenv_python: python3

# - name: Run database migrations
#   command: >
#     /home/{{ ansible_ssh_user }}/{{ app_name }}/env/bin/python
#     ./manage.py
#     db
#     upgrade
#   args:
#     chdir: /home/{{ ansible_ssh_user }}/{{ app_name }}
