---
# defaults file for ec2-deploy

# application source code
repo_url: https://github.com/{{ github_user }}/{{ app_name }}.git
# system packages
packages:
  - python3-pip
  - python3-dev
  - git
  - tree
  - nginx
  - rabbitmq-server
pip_core:
  - pip
  - setuptools
  - wheel
python_core:
  - virtualenv
postgres_core:
  - postgresql
  - postgresql-contrib
  - postgresql-client-common
  - python3-psycopg2
# environment variables
os_environment:
  - key: SQLALCHEMY_DATABASE_URI
    value : postgresql+psycopg2://{{ postgres_user }}:{{ postgres_password }}@localhost:5432/{{ postgres_database }}
  - key: CELERY_BROKER_URL
    value : amqp://{{ rabbitmq_user }}:{{ rabbitmq_password }}@localhost:4369{{ rabbitmq_vhost }}
  - key: FLASK_CONFIG_PATH
    value: "{{ flask_config_path }}"
  - key: AUTH_TOKEN
    value: supersecrettoken
# application
wsgi_path: "{{ entry_point }}.core.wsgi"
# log files
log_file_directory: /home/{{ ansible_ssh_user }}/log
gunicorn_error_log: {{ log_file_directory }}/gunicorn/gunicorn-error.log
gunicorn_access_log: {{ log_file_directory }}/gunicorn/gunicorn-access.log
